# DEFINIR VALORES PARA A CAMADA BACKEND #

backend:
  enabled: true             # Deve ser habilitado se o projeto contér a chamada frontend
  replicas: 1               # Quantidade de pods que rodará a aplicação
  containerPort: 8080       # Porta default para todos projetos
  cpuLimit: 600m            # Limite de CPU que um pod, pode utilizar. (valor default)
  cpuRequest: 300m          # Solicitação inicial de CPU para o pod. (valor default)
  memoryLimit: 512Mi        # Limite de RAM que um pod, pode utilizar. (valor default) 
  memoryRequest: 384Mi      # Solicitação inicial de RAM para o pod. (valor default)