{{- if .Values.frontend.enabled -}}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- $name := printf "%s-frontend" $name -}}



kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}

spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      volumes:
        - name: site
          configMap:
            name: site-^[a-z0-9]{10}$
        - name: {{ $name }}
          image: registry.access.redhat.com/ubi9/nginx-122
          command: ["nginx", "-g", "daemon off;"]          
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: {{ .Values.frontend.cpuLimit }}
              memory: {{ .Values.frontend.memoryLimit }}
            requests:
              cpu: {{ .Values.frontend.cpuRequest }}
              memory: {{ .Values.frontend.memoryRequest }}
          volumeMounts:
            - name: site
              mountPath: /
{{- end -}}
