{{ if .Values.secrets }}
{{ $name := .Release.Name | trimSuffix "-hom" | trimSuffix "-int" | trimSuffix "-prd"}}
{{- $name := printf "%s-backend" $name -}}
{{ range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    app: {{ $name }}
data:
{{ range $inst := $secret.keys }}

  {{ if $inst.encoded }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | quote }}
  {{ else }}
    {{ default "" $inst.name }}: {{ default "" $inst.value | b64enc | quote }}
  {{ end }}
    
{{ end }}
---
{{ end }}
{{ end }}